### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by zeus1999** [sangdth/password-manager#1]
i cloned your git rep and receive this error after installing all modules and run "npm run build"

https://pastebin.com/u7vCkUSu

```

`
> node .electron-vue/build.js && electron-builder

 ___              __                        __                       ___       __
/\_ \       __   /\ \__     ____           /\ \       __  __   __   /\_ \     /\ \
\//\ \    / ,.`\ \ \ ,_\   / ,__\  _______ \ \ \____ /\ \/\ \ /\_\  \//\ \    \_\ \
  \_\ \_ /\  __/  \ \ \/  /\__, `\/\______\ \ \  ,. \\ \ \_\ \\/\ \   \_\ \_ /\ ,. \
  /\____\\ \____\  \ \ \_ \/\____/\/______/  \ \____/ \ \____/ \ \ \  /\____\\ \____\
  \/____/ \/____/   \ \__\ \/___/             \/___/   \/___/   \/_/  \/____/ \/___ /
                     \/__/

  - building main process
  - building renderer process
  √ building main process
  | building renderer process
C:\Users\tobias.jung\Documents\workspace\password-manager-master\node_modules\html-webpack-plugin\lib\compiler.js:81
        var outputName = compilation.mainTemplate.applyPluginsWaterfall('asset-path', outputOptions.filename, {
                                                  ^

TypeError: compilation.mainTemplate.applyPluginsWaterfall is not a function
    at C:\Users\tobias.jung\Documents\workspace\password-manager-master\node_modules\html-webpack-plugin\lib\compiler.js:81:51
    at compile (C:\Users\tobias.jung\Documents\workspace\password-manager-master\node_modules\webpack\lib\Compiler.js:290:11)
    at hooks.afterCompile.callAsync.err (C:\Users\tobias.jung\Documents\workspace\password-manager-master\node_modules\webpack\lib\Compiler.js:547:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\tobias.jung\Documents\workspace\password-manager-master\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\tobias.jung\Documents\workspace\password-manager-master\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)
    at compilation.seal.err (C:\Users\tobias.jung\Documents\workspace\password-manager-master\node_modules\webpack\lib\Compiler.js:544:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\tobias.jung\Documents\workspace\password-manager-master\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\tobias.jung\Documents\workspace\password-manager-master\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (C:\Users\tobias.jung\Documents\workspace\password-manager-master\node_modules\webpack\lib\Compilation.js:1296:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\tobias.jung\Documents\workspace\password-manager-master\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\tobias.jung\Documents\workspace\password-manager-master\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (C:\Users\tobias.jung\Documents\workspace\password-manager-master\node_modules\webpack\lib\Compilation.js:1287:32)
    at _err1 (eval at create (C:\Users\tobias.jung\Documents\workspace\password-manager-master\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:16:1)
    at C:\Users\tobias.jung\Documents\workspace\password-manager-master\node_modules\uglifyjs-webpack-plugin\dist\index.js:287:11
    at Runner.runTasks (C:\Users\tobias.jung\Documents\workspace\password-manager-master\node_modules\uglifyjs-webpack-plugin\dist\uglify\Runner.js:67:9)
    at UglifyJsPlugin.optimizeFn (C:\Users\tobias.jung\Documents\workspace\password-manager-master\node_modules\uglifyjs-webpack-plugin\dist\index.js:198:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! password-manager@2.2.3 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the password-manager@2.2.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tobias.jung\AppData\Roaming\npm-cache\_logs\2018-10-14T01_13_56_006Z-debug.log
PS C:\Users\tobias.jung\Documents\workspace\password-manager-master>
`
```

**Comment by sangdth** [comment]
I'm working on some uprades of this app, will push the patch also some new features later next week.

**Comment by sangdth** [comment]
@zeus1999 First beta release is available, please check https://github.com/sangdth/password-manager/releases/tag/v3.0.0-beta.1
